name: Build, Push, and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
    
    - name: Train model (for testing)
      run: python model/train.py
    
    - name: Run tests
      run: python -m pytest tests/ -v
    
    - name: Run linting (optional)
      run: |
        pip install flake8
        flake8 app/ model/ --count --select=E9,F63,F7,F82 --show-source --statistics

  build_and_push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Train model for Docker build
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        python model/train.py

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/mlops-demo:latest,${{ secrets.DOCKER_USERNAME }}/mlops-demo:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production
    
    steps:
    - name: Deploy to Render
      run: |
        echo "🚀 Triggering deployment to Render..."
        curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
        echo "✅ Deploy hook triggered successfully!"
        
    - name: Wait for deployment
      run: |
        echo "⏱️ Waiting for deployment to complete..."
        sleep 90
        
    - name: Health check
      run: |
        echo "🔍 Checking if app is healthy..."
        for i in {1..5}; do
          if curl -f "${{ secrets.RENDER_APP_URL }}" -m 10; then
            echo "✅ App is live and healthy!"
            echo "🌐 Your app is available at: ${{ secrets.RENDER_APP_URL }}"
            exit 0
          fi
          echo "⏳ Attempt $i failed, retrying in 30 seconds..."
          sleep 30
        done
        echo "❌ Health check failed after 5 attempts"
        exit 1
        
    - name: Deployment Success
      run: |
        echo "🎉 Deployment completed successfully!"
        echo "🌐 Live at: ${{ secrets.RENDER_APP_URL }}"
        echo "🔄 Future pushes to main will auto-deploy!"